trigger:
- master

pool:
  vmImage: 'ubuntu-20.04'

steps:
    # - task: Bash@3
    #   displayName: See Files
    #   inputs:
    #     targetType: 'inline'
    #     script: |
    #       echo pwd
    #       pwd
    #       echo ls -la
    #       ls -la
    #       echo rm -rf git
    #       rm -rf .git
    #       echo rm -rf .github
    #       rm -rf .github
    #       echo rm -rf .husky
    #       rm -rf .husky
    #       echo rm -rf .gitignore
    #       rm -rf .gitignore
    #       echo ls -la
    #       ls -la
    #       echo check /var/lib/waagent/custom-script/download
    #       sudo ls -la /var/lib/waagent/custom-script/download/*/
    #       echo check /var/lib/waagent/
    #       sudo ls -la /var/lib/waagent/

#    - task: Bash@3
#      displayName: Install Azure CLI version 2.53.1
#      inputs:
#        targetType: 'inline'
#        script: |
#          sudo apt-get purge --auto-remove azure-cli
#          pip3 install azure-cli==2.53.1

    - task: AzureCLI@2
      displayName: Upload reports to Azure Storage
      inputs:
        azureSubscription: 'Sajan Azure Internal Subs'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $PSVersionTable
          az storage fs directory generate-sas --account-name sajanstorageaccount --file-system mycontainer1 --name '/' --permissions dlrw
          az storage fs directory upload --account-name sajanstorageaccount -f mycontainer -d "pipeline_run_03" -s "*" --recursive --debug
          echo "The HTML report can be found here: nothing"

#    - task: Bash@3
#      displayName: See Files
#      inputs:
#        targetType: 'inline'
#        script: |
#          echo ls -la /home/vsts/
#          ls -la /home/vsts/
#          echo ls -la /home/vsts/.azcopy
#          ls -la /home/vsts/.azcopy
